indee_video_engine:
  # keeping the version number, so we can further maintain
  # some of deprecations
  version: "v1"
  log:
    enable: true
    level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

  # engine related basic configs
  configs:
    # you can configure the storage engine,
    # as of now we only support sqlite
    db:
      enable: true
      service: "sqlite"
    # run the engine as a api server, by default
    # it is just cli
    server:
      enable: true
      port: 8001

      # enabling prometheus metrics, for the further
      # analytics, and mastrics
      metrics:
        enable: false
        port: 9090
        
  # cache related configs
  cache:
    # ( os.CWD, cache.dir ), cache dir, the main working dir
    # for all video processing
    dirname: "%WORDIR/output/%DATE/%TIMESTAMP/"
  
  # video processing related configs
  banto:
    banto_dir: "banto" # banto dir, where all the banto files are stored, should be in the root of the project
    fragment: 8000 # 8 seconds